"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 16:40:36.007818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

SONG_VIEW = """
CREATE VIEW song_effective_ratings AS
SELECT user_id, song_id AS target_id, (score / 2.0)::numeric(2,1) AS stars,
       false AS is_derived, 0 AS song_count
FROM ratings
WHERE song_id IS NOT NULL
"""

# an explicit album or artist rating overrides the average of that user's song ratings
DERIVED_VIEW = """
CREATE VIEW {kind}_effective_ratings AS
WITH derived AS NOT MATERIALIZED (
    SELECT r.user_id, {group_column} AS target_id,
           ROUND(AVG(r.score) / 2.0, 1) AS stars, COUNT(*)::int AS song_count
    FROM ratings r
    JOIN {song_join}
    GROUP BY r.user_id, {group_column}
)
SELECT r.user_id, r.{kind}_id AS target_id, (r.score / 2.0)::numeric(2,1) AS stars,
       false AS is_derived, COALESCE(d.song_count, 0) AS song_count
FROM ratings r
LEFT JOIN derived d ON d.user_id = r.user_id AND d.target_id = r.{kind}_id
WHERE r.{kind}_id IS NOT NULL
UNION ALL
SELECT d.user_id, d.target_id, d.stars::numeric(2,1), true, d.song_count
FROM derived d
WHERE NOT EXISTS (
    SELECT 1 FROM ratings r WHERE r.user_id = d.user_id AND r.{kind}_id = d.target_id
)
"""

ALBUM_VIEW = DERIVED_VIEW.format(
    kind="album", group_column="x.album_id", song_join="album_songs x ON x.song_id = r.song_id"
)
ARTIST_VIEW = DERIVED_VIEW.format(
    kind="artist", group_column="x.artist_id", song_join="songs x ON x.id = r.song_id"
)
VIEWS = ("song_effective_ratings", "album_effective_ratings", "artist_effective_ratings")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('mbid', name=op.f('uq_artists_mbid'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_albums_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums')),
    sa.UniqueConstraint('mbid', name=op.f('uq_albums_mbid'))
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist_id'), ['artist_id'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("description <> ''", name=op.f('ck_playlists_description_not_blank')),
    sa.CheckConstraint("name <> ''", name=op.f('ck_playlists_name_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_playlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_user_id'), ['user_id'], unique=False)

    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('disambiguation', sa.String(length=500), nullable=True),
    sa.Column('length_ms', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_songs_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_songs')),
    sa.UniqueConstraint('mbid', name=op.f('uq_songs_mbid'))
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_artist_id'), ['artist_id'], unique=False)

    op.create_table('album_songs',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_songs_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_album_songs_song_id_songs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'song_id', name=op.f('pk_album_songs'))
    )
    with op.batch_alter_table('album_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_songs_song_id'), ['song_id'], unique=False)

    op.create_table('artist_top_songs',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_top_songs_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_artist_top_songs_song_id_songs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', 'rank', name=op.f('pk_artist_top_songs'))
    )
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_songs_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_playlist_songs_song_id_songs')),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id', name=op.f('pk_playlist_songs')),
    sa.UniqueConstraint('playlist_id', 'position', deferrable=True, initially='DEFERRED', name=op.f('uq_playlist_songs_playlist_id_position'))
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('review', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review <> ''", name=op.f('ck_ratings_review_not_blank')),
    sa.CheckConstraint('num_nonnulls(song_id, album_id, artist_id) = 1', name=op.f('ck_ratings_one_target')),
    sa.CheckConstraint('score BETWEEN 1 AND 10', name=op.f('ck_ratings_score_range')),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_ratings_album_id_albums')),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_ratings_artist_id_artists')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_ratings_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('user_id', 'album_id', name=op.f('uq_ratings_user_id_album_id')),
    sa.UniqueConstraint('user_id', 'artist_id', name=op.f('uq_ratings_user_id_artist_id')),
    sa.UniqueConstraint('user_id', 'song_id', name=op.f('uq_ratings_user_id_song_id'))
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###
    for view in (SONG_VIEW, ALBUM_VIEW, ARTIST_VIEW):
        op.execute(view)


def downgrade():
    for view in VIEWS:
        op.execute(f"DROP VIEW {view}")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_song_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_artist_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_album_id'))

    op.drop_table('ratings')
    op.drop_table('playlist_songs')
    op.drop_table('artist_top_songs')
    with op.batch_alter_table('album_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_songs_song_id'))

    op.drop_table('album_songs')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_artist_id'))

    op.drop_table('songs')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_user_id'))

    op.drop_table('playlists')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_artist_id'))

    op.drop_table('albums')
    op.drop_table('users')
    op.drop_table('artists')
    # ### end Alembic commands ###
